/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jpanel;

/**
 *
 * @author Николай
 */
public class JPanelTeken extends javax.swing.JPanel {

    private javax.swing.JButton jbtnJPT_Cancel;
    private javax.swing.JButton jbtnJPT_Enter;
    private javax.swing.JLabel jlabJPIDC_ConsumptionSummer;
    private javax.swing.JLabel jlabJPT_Coiled;
    private javax.swing.JLabel jlabJPT_Km;
    private javax.swing.JLabel jlabJPT_NeedCoiled;
    private javax.swing.JLabel jlabJPT_NeedCoiledRes;
    private javax.swing.JLabel jlabJPT_Teken;
    private javax.swing.JTextField jtfJPD_Coiled;
    private javax.swing.JTextField jtfJPIDC_ConsumptionSummer;
    private javax.swing.JTextField jtfJPT_Taken;
    
    private String getTeken(){
        return jtfJPT_Taken.getText();
    }
    
    public JPanelTeken() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jlabJPT_Teken = new javax.swing.JLabel();
        jtfJPT_Taken = new javax.swing.JTextField();
        jlabJPT_Coiled = new javax.swing.JLabel();
        jtfJPD_Coiled = new javax.swing.JTextField();
        jlabJPT_NeedCoiled = new javax.swing.JLabel();
        jlabJPT_NeedCoiledRes = new javax.swing.JLabel();
        jlabJPT_Km = new javax.swing.JLabel();
        jbtnJPT_Cancel = new javax.swing.JButton();
        jbtnJPT_Enter = new javax.swing.JButton();
        jlabJPIDC_ConsumptionSummer = new javax.swing.JLabel();
        jtfJPIDC_ConsumptionSummer = new javax.swing.JTextField();

        setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Заправлено", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Times New Roman", 1, 16))); // NOI18N
        setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        jlabJPT_Teken.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jlabJPT_Teken.setText("Заправлено :");

        jtfJPT_Taken.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jtfJPT_Taken.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfJPT_TakenActionPerformed(evt);
            }
        });

        jlabJPT_Coiled.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jlabJPT_Coiled.setText("Намотано :");

        jlabJPT_NeedCoiled.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jlabJPT_NeedCoiled.setText("Намотать :");

        jlabJPT_NeedCoiledRes.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jlabJPT_NeedCoiledRes.setText("0");

        jlabJPT_Km.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jlabJPT_Km.setText("км.");

        jbtnJPT_Cancel.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jbtnJPT_Cancel.setText("Отмена");
        jbtnJPT_Cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnJPT_CancelActionPerformed(evt);
            }
        });

        jbtnJPT_Enter.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jbtnJPT_Enter.setText("Ввести");
        jbtnJPT_Enter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnJPT_EnterActionPerformed(evt);
            }
        });

        jlabJPIDC_ConsumptionSummer.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jlabJPIDC_ConsumptionSummer.setText("Расход топлива :");

        jtfJPIDC_ConsumptionSummer.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jtfJPIDC_ConsumptionSummer.setToolTipText("Введите количество расходуемого топлива на 100 км.");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jlabJPT_Teken)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtfJPT_Taken, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jbtnJPT_Enter)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jlabJPT_NeedCoiled)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jlabJPT_NeedCoiledRes, javax.swing.GroupLayout.PREFERRED_SIZE, 7, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jlabJPT_Km)))
                        .addGap(18, 18, 18)
                        .addComponent(jbtnJPT_Cancel))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(jlabJPT_Coiled)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jtfJPD_Coiled))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(jlabJPIDC_ConsumptionSummer)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jtfJPIDC_ConsumptionSummer, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlabJPT_Teken)
                    .addComponent(jtfJPT_Taken, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlabJPT_Coiled)
                    .addComponent(jtfJPD_Coiled, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlabJPIDC_ConsumptionSummer)
                    .addComponent(jtfJPIDC_ConsumptionSummer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlabJPT_NeedCoiled)
                    .addComponent(jlabJPT_NeedCoiledRes)
                    .addComponent(jlabJPT_Km))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnJPT_Enter)
                    .addComponent(jbtnJPT_Cancel))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>                        

    private void jtfJPT_TakenActionPerformed(java.awt.event.ActionEvent evt) {                                             
        System.out.println(getTeken());
    }                                            

    private void jbtnJPT_EnterActionPerformed(java.awt.event.ActionEvent evt) {                                              
        // TODO add your handling code here:
    }                                             

    private void jbtnJPT_CancelActionPerformed(java.awt.event.ActionEvent evt) {                                               
        // TODO add your handling code here:
    }                                              


                        
    
                      
}
